# Generated by Django 4.2.16 on 2026-05-03 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("episode", models.CharField(max_length=20, verbose_name="期数")),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("tag", models.CharField(max_length=50, verbose_name="标签")),
                ("date", models.CharField(max_length=30, verbose_name="日期")),
                ("youtuber", models.CharField(max_length=100, verbose_name="博主")),
                (
                    "topic",
                    models.CharField(blank=True, max_length=100, verbose_name="话题"),
                ),
                (
                    "thumbnail",
                    models.URLField(max_length=500, verbose_name="缩略图URL"),
                ),
                ("video_url", models.URLField(max_length=500, verbose_name="视频URL")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "视频课程",
                "verbose_name_plural": "视频课程",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chinese_text", models.TextField(blank=True, verbose_name="中文文本")),
                ("english_text", models.TextField(blank=True, verbose_name="英文文本")),
                (
                    "phrases",
                    models.JSONField(blank=True, default=list, verbose_name="短语列表"),
                ),
                (
                    "sentences",
                    models.JSONField(blank=True, default=list, verbose_name="单句练习"),
                ),
                (
                    "highlight_phrases",
                    models.JSONField(
                        blank=True, default=list, verbose_name="高亮短语配置"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "video",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程详情",
                "verbose_name_plural": "课程详情",
            },
        ),
        migrations.CreateModel(
            name="UserFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_videos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户收藏",
                "verbose_name_plural": "用户收藏",
                "unique_together": {("user", "video")},
            },
        ),
    ]
